### ISSUE TITLE
我提交手机号后提示这个，也没收到短信

### ISSUE THREAD

**Issue by tanjiancheng** [joe-lz/TodoKit#11]
![image](https://user-images.githubusercontent.com/7401570/37131574-e7808b46-22c3-11e8-9651-1e9e71c8d76f.png)

**Comment by joe-lz** [comment]
服务器被停止了，需要使用的话，可以自己搭建服务器，下载源码即可

**Comment by joe-lz** [comment]
@tanjiancheng 服务器续费了，可以体验了，想正式使用的话，建议自己搭建服务器
