### ISSUE TITLE
New logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [joe-lz/TodoKit#13]
Hi, I want to design a new logo for the project completely free...

**Comment by joe-lz** [comment]
That’s cool,thank you

**Comment by Arslanshn** [comment]
hello I made the logo I hope you like:)
https://drive.google.com/drive/folders/1iBmoexh5bj6lpNqkzO4Valw7LbSX2zIc?usp=sharing

**Comment by Arslanshn** [comment]
Hi, What is your thoughts about the logo:-)

**Comment by Esmio** [comment]
to be honest, sorry its ugly.
